###############
## 
####


GPU: [1,2]

VERBOSE: True

MODEL:
  MODE: 'De'
  SESSION: 'CAPTNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 10000000
  NUM_EPOCHS: 100000
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 500
  RESUME: True
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: './tes' # path to training data
  VAL_DIR: './Datasets/GoPr/test'    # path to validation data
  VAL_DIR2: './RainDatasets/test/Rain100L'    # path to validation data
  SAVE_DIR: './checkpoints'     # path to save models and images
  # SAVE_IMAGES: False
